const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "254114906989";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "true"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "254114906989";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "true";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "joab",

  sessionName:process.env.SESSION_ID || "SUHAIL_10_41_09_11_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMDYsXG4gICAgICAgIDIxNyxcbiAgICAgICAgOSxcbiAgICAgICAgMjQxLFxuICAgICAgICA5MixcbiAgICAgICAgMTA3LFxuICAgICAgICAxNjYsXG4gICAgICAgIDQwLFxuICAgICAgICAxMzksXG4gICAgICAgIDE4NixcbiAgICAgICAgMTU3LFxuICAgICAgICA0NCxcbiAgICAgICAgMjQwLFxuICAgICAgICA4MixcbiAgICAgICAgMTQ5LFxuICAgICAgICAxMjMsXG4gICAgICAgIDc0LFxuICAgICAgICAyMjUsXG4gICAgICAgIDE2LFxuICAgICAgICAxNDIsXG4gICAgICAgIDk2LFxuICAgICAgICA2OCxcbiAgICAgICAgMTQwLFxuICAgICAgICAyMDcsXG4gICAgICAgIDkxLFxuICAgICAgICAyNTMsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMjZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjEsXG4gICAgICAgIDYsXG4gICAgICAgIDIwNixcbiAgICAgICAgMjAyLFxuICAgICAgICA4OSxcbiAgICAgICAgMTU4LFxuICAgICAgICAyNTIsXG4gICAgICAgIDI4LFxuICAgICAgICA0NixcbiAgICAgICAgMzksXG4gICAgICAgIDk3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDk1LFxuICAgICAgICAxOTEsXG4gICAgICAgIDg5LFxuICAgICAgICAxNjcsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjA5LFxuICAgICAgICAxODcsXG4gICAgICAgIDIyLFxuICAgICAgICAyOCxcbiAgICAgICAgMjMsXG4gICAgICAgIDYyLFxuICAgICAgICAxMjIsXG4gICAgICAgIDIzNixcbiAgICAgICAgNzUsXG4gICAgICAgIDQ3LFxuICAgICAgICA1MSxcbiAgICAgICAgOTYsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTUwLFxuICAgICAgICA1NFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDUxLFxuICAgICAgICAxMjYsXG4gICAgICAgIDE4LFxuICAgICAgICAzLFxuICAgICAgICA5MSxcbiAgICAgICAgODAsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTgzLFxuICAgICAgICAyMjksXG4gICAgICAgIDIyMCxcbiAgICAgICAgODcsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTI3LFxuICAgICAgICA0NixcbiAgICAgICAgNDQsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMyxcbiAgICAgICAgMjQwLFxuICAgICAgICAzMyxcbiAgICAgICAgNixcbiAgICAgICAgMTgsXG4gICAgICAgIDE4NyxcbiAgICAgICAgNDYsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTUyLFxuICAgICAgICA3LFxuICAgICAgICAyMjEsXG4gICAgICAgIDU2LFxuICAgICAgICA2LFxuICAgICAgICAxOTQsXG4gICAgICAgIDY1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwMixcbiAgICAgICAgNzIsXG4gICAgICAgIDE4LFxuICAgICAgICAyNTIsXG4gICAgICAgIDIwLFxuICAgICAgICAzOSxcbiAgICAgICAgMTQ3LFxuICAgICAgICA1NSxcbiAgICAgICAgNDEsXG4gICAgICAgIDkwLFxuICAgICAgICAzNCxcbiAgICAgICAgMTI4LFxuICAgICAgICAxMzUsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTIyLFxuICAgICAgICAyMTYsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTQwLFxuICAgICAgICAyNTUsXG4gICAgICAgIDEyOCxcbiAgICAgICAgNDgsXG4gICAgICAgIDgwLFxuICAgICAgICA3NCxcbiAgICAgICAgMTQzLFxuICAgICAgICAyMTYsXG4gICAgICAgIDY4LFxuICAgICAgICAyMTIsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjA0LFxuICAgICAgICAyMDgsXG4gICAgICAgIDUwLFxuICAgICAgICAzM1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDg2LFxuICAgICAgICAyMjQsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTA5LFxuICAgICAgICAxNzEsXG4gICAgICAgIDExLFxuICAgICAgICAxMzUsXG4gICAgICAgIDcsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTg3LFxuICAgICAgICAyMzEsXG4gICAgICAgIDYxLFxuICAgICAgICAxNDksXG4gICAgICAgIDk1LFxuICAgICAgICAyMDYsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNDksXG4gICAgICAgIDg0LFxuICAgICAgICAxODAsXG4gICAgICAgIDE5OCxcbiAgICAgICAgOTcsXG4gICAgICAgIDgxLFxuICAgICAgICAyNixcbiAgICAgICAgMTA4LFxuICAgICAgICAxMzMsXG4gICAgICAgIDEyLFxuICAgICAgICA3N1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2MSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxNTIsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTU4LFxuICAgICAgICAyMTksXG4gICAgICAgIDQ5LFxuICAgICAgICA2MixcbiAgICAgICAgMjUxLFxuICAgICAgICAyMzgsXG4gICAgICAgIDE0MCxcbiAgICAgICAgODIsXG4gICAgICAgIDM1LFxuICAgICAgICAyMDAsXG4gICAgICAgIDgxLFxuICAgICAgICAxOTYsXG4gICAgICAgIDI1LFxuICAgICAgICAyMzQsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTE5LFxuICAgICAgICA3LFxuICAgICAgICAyMzksXG4gICAgICAgIDE3NSxcbiAgICAgICAgNDcsXG4gICAgICAgIDExNixcbiAgICAgICAgMjE0LFxuICAgICAgICAxMDcsXG4gICAgICAgIDI4LFxuICAgICAgICAyNSxcbiAgICAgICAgMjIxLFxuICAgICAgICAyNTIsXG4gICAgICAgIDEwNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAzMixcbiAgICAgICAgICA5LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICA2MixcbiAgICAgICAgICAyMSxcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyOSxcbiAgICAgICAgICAzNSxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICA4NyxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAxLFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTA0XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE4OSxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICA4NixcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgNixcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDEyN1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjE1LFxuICAgICAgICAxMzEsXG4gICAgICAgIDcxLFxuICAgICAgICAyOCxcbiAgICAgICAgNDQsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTM1LFxuICAgICAgICAyMCxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNTksXG4gICAgICAgIDY4LFxuICAgICAgICAxNTEsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMzIsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNixcbiAgICAgICAgMjIzLFxuICAgICAgICAxLFxuICAgICAgICA0NixcbiAgICAgICAgMzMsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTIxLFxuICAgICAgICAxMzksXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTY2LFxuICAgICAgICAwLFxuICAgICAgICAyMzAsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMjA3LFxuICAgICAgICAyMzUsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTQzLFxuICAgICAgICAyMTgsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMjM0LFxuICAgICAgICA3OCxcbiAgICAgICAgMTMyLFxuICAgICAgICAxODIsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTI5LFxuICAgICAgICA4OCxcbiAgICAgICAgMTMsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMjIwLFxuICAgICAgICAxMTYsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMjAwLFxuICAgICAgICAyMzMsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMzEsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjExLFxuICAgICAgICAxMzYsXG4gICAgICAgIDEzMyxcbiAgICAgICAgNzUsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTc4LFxuICAgICAgICA3OSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA2NSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJVM1BIUnlqUGJudXRUTnp1VUgvTHVKZEE5ZFM1c1Q2WG5wdXlCK2ZXd25nPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1NDExNDkwNjk4OUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNTczQTkxMTUxRTBGQjhEMkQ3MkE2NENFMjQ1ODFDMTdcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI2MDUxMjk5XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU0MTE0OTA2OTg5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI2NjAwQTU2QkNBREMwNjVFRUVEMjgyQUU5MjJEMTkyOFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjYwNTEzMDBcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwic1dzM1BDUzBRMy1YQ0dyMTVPYzc5Z1wiLFxuICBcInBob25lSWRcIjogXCJiZmVlOWQ3ZS1iOGQ0LTQxNzctYTY2Mi00ZGUxZGE5MGFjNWRcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTUzLFxuICAgICAgNDgsXG4gICAgICAxNTMsXG4gICAgICAyMTUsXG4gICAgICAyNTQsXG4gICAgICAyNCxcbiAgICAgIDMsXG4gICAgICAxOTQsXG4gICAgICAxOTEsXG4gICAgICAxOTUsXG4gICAgICAyMzgsXG4gICAgICAyNTEsXG4gICAgICAyMzMsXG4gICAgICAyNDMsXG4gICAgICAxOTksXG4gICAgICAxNSxcbiAgICAgIDE0MCxcbiAgICAgIDUzLFxuICAgICAgMTUwLFxuICAgICAgMTY3XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDI0NyxcbiAgICAgIDMwLFxuICAgICAgMTk3LFxuICAgICAgNTcsXG4gICAgICAyMzEsXG4gICAgICAyNDYsXG4gICAgICAxMDQsXG4gICAgICAyMDQsXG4gICAgICAxNjQsXG4gICAgICA3MSxcbiAgICAgIDEzMCxcbiAgICAgIDY1LFxuICAgICAgMzgsXG4gICAgICAxNjksXG4gICAgICAxMDgsXG4gICAgICAyNSxcbiAgICAgIDY0LFxuICAgICAgMTE5LFxuICAgICAgNTEsXG4gICAgICAxMzJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiU0pMQTJBMk1cIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjI1NDExNDkwNjk4OToyN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiNDk5OTgxMzM3MjcyODU6MjdAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiR2VlIFN0ZXZlXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSkhQMjZZSEVOem5oYmNHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJ4bHJKUXEvTnZKOWwrcGRBWUdVWFVXblV5blp4WjBpUE5wQjI4QThoUkd3PVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIm1na2VkQzNISDBVUDZpWEZDV2hXYzJqNmlwM2FWLzg4RDNMbE9ZcHE5N3dXdnB6OU5aRXo3L1cyRDBWMktqY21zZUo3YWQwZHBidnNyeUJxRjkwdEJBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIm93N2c1QzRxQlppRFc1Q3RoTE9pTXY5S2RrQUdodnBmazliZE9hTDdnZW5mOUZ3VEFpb21iTTJjam1JZ0swRDlxaU4yRkxCMHNVMnJrcWRvbkFCZEFRPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjI1NDExNDkwNjk4OToyN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMTA4XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjYwNTEyOTYsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFBbFJcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFsUi5qc29uIjogIntcImtleURhdGFcIjpcIkR2TnZ3UWpKUHRtR0YwUVdiZGpBYUZNdlpIYUZsMFl2V1VqYjNFSE1rY2c9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTk2MDI0MTA0MSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI2MDUxMjk4MTI1XCJ9Igp9",
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
